name: Google Books E2E Tests
on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

concurrency:
  group: google-books-e2e-tests-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          path: google-books-ui-test-automation
          repository: mmdfaisal1/google-books-ui-test-automation
          token: ${{ secrets.GH_API_ACCESS_TOKEN }}

      - name: Set up Node 20
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65
        with:
          node-version: 20

      - name: Install dependencies and Playwright Browser
        working-directory: google-books-ui-test-automation
        run: |
          yarn install --frozen-lockfile
          npx playwright install --with-deps chromium

      - name: Run E2E Tests
        working-directory: google-books-ui-test-automation
        run: yarn test

      - name: Upload Test Reports
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32
        if: always()
        with:
          name: Test Reports
          path: google-books-ui-test-automation/reports/**/*
          retention-days: 14
